FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=securepassword
ENV MYSQL_DATABASE=automotosprint
ENV MYSQL_USER=gabriele
ENV MYSQL_PASSWORD=Gabry678
ENV PMA_HOST: db
COPY sql_auto/ /docker-entrypoint-initdb.d/